### ISSUE TITLE
How to properly integrate DTM in abp application

### ISSUE THREAD

**Issue by leonkosak** [EasyAbp/Abp.EventBus.Boxes.Dtm#9]
Hi,

Exception:
```
2023-05-19 14:28:58.594 +02:00 [ERR] Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.get_IsCompleted()
   at EasyAbp.Abp.EventBus.Boxes.Dtm.AbpDtmgRPCClient.DtmGrpcCall(TransBase transBase, String operation)
   at Dtmgrpc.MsgGrpc.Prepare(String queryPrepared, CancellationToken cancellationToken)
   at EasyAbp.Abp.EventBus.Boxes.Dtm.GrpcDtmMessageManager.PrepareTransMessagesAsync(DtmOutboxEventBag eventBag, CancellationToken cancellationToken)
   at EasyAbp.Abp.EventBus.Boxes.Dtm.GrpcDtmMessageManager.PrepareAndInsertBarriersAsync(DtmOutboxEventBag eventBag, CancellationToken cancellationToken)
   at EasyAbp.Abp.EventBus.Distributed.Dtm.DtmUnitOfWork.CommitTransactionsAsync()
   at Volo.Abp.Uow.UnitOfWork.CompleteAsync(CancellationToken cancellationToken)
   at Volo.Abp.AspNetCore.Uow.AbpUnitOfWorkMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Volo.Abp.AspNetCore.ExceptionHandling.AbpExceptionHandlingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
```

I have a newly generated abp application (v7.2.2) (tiered, mvc, ef core - postgres).

Added configuration and code in **HttpApi.Host** (deployable) project.

appsettings.json
```
"RabbitMQ": {
    "Connections": {
      "Default": {
        "HostName": "localhost",
        "Port": "5672",
        "UserName": "guest",
        "Password": "guest"
      }
    },
    "EventBus": {
      "ClientName": "rabbit@dev-rabbit",
      "ExchangeName": "amq.direct"
    }
  },
  "DTM": {
    "ActionApiToken": "1q2w3e",
    "AppGrpcUrl": "http://localhost:54358",
    "DtmGrpcUrl": "http://localhost:36790"
  }
```

Additional code in xxxxHttpApiHostModule.

DependsOn:
```
typeof(AbpEventBusRabbitMqModule),
    typeof(AbpEventBusBoxesDtmGrpcModule),
    typeof(AbpEventBusBoxesDtmEntityFrameworkCoreModule)
```

Method ConfigureServices
```
Configure<AbpDistributedEventBusOptions>(options =>
        {
            options.Outboxes.Configure(config =>
            {
                config.UseDbContextWithDtmOutbox<AbpDtmApp1DbContext>();
            });

            options.Inboxes.Configure(config =>
            {
                config.UseDbContextWithDtmInbox<AbpDtmApp1DbContext>();
            });
        });

        // Use `AddDtmOutbox` and `AddDtmInbox` separately if you only need one of them.
        context.Services.AddDtmBoxes();

        context.Services.AddGrpc();
        context.Services.AddAbpDtmGrpc(options =>
        {
            options.ActionApiToken = "1q2w3e";  // DTM Server invokes app's action APIs with this token for authorization.
            options.AppGrpcUrl = "https://localhost:44336";  // Base URL for DTM Server to invoke the current app. Only HTTP now!
            options.DtmGrpcUrl = "http://127.0.0.1:36790";  // Base URL for the current app to invoke DTM Server.
        });
```

Method OnApplicationInitialization
```
app.UseConfiguredEndpoints(endpoints =>
        {
            endpoints.MapAbpDtmGrpcService();
        });
```

Connection to RabbitMQ works.
DTM is launched as .exe application and I can access GUI via localhost:36789

Thank you for helping.

**Comment by gdlcf88** [comment]
Hi, could you please debug to find which line caused the NullReferenceException?

**Comment by leonkosak** [comment]
Sorry for the late response @gdlcf88.

I'll describe my scenario.
**Maybe this should be added as an additional sample in a repo.** :-)

1) Create new abp applications (tiered architecture, mvc - **it doesn't matter frontend technology - only that backend is tiered**).
`abp new MyAbpDtmApp1 -t app -u mvc --tiered -dbms PostgreSQL -v 7.2.2`
and
`abp new MyAbpDtmApp2 -t app -u mvc --tiered -dbms PostgreSQL -v 7.2.2`

2) Pull and start RabbitMQ for Docker
`docker pull rabbitmq:management`
`docker run -d --hostname mycompany-rabbit --name mycompany-dev-rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:management`

3) Get and run DTM server.
I currently use **windows_amd64** binary from here: https://github.com/dtm-labs/dtm/releases/latest
It is running, because I can access URL and see GUI: http://localhost:36789/
**Question**
How to properly run (`docker run` command with parameters and configuration) for an official DTM image (https://hub.docker.com/r/yedf/dtm/)?
I found this command:
`docker run --name dtm -p 36789:36789 -p 36790:36790 -e STORE_DRIVER=mysql -e STORE_HOST=localhost -e STORE_USER=root -e STORE_PASSWORD= -e STORE_ PORT=3306 -e IS_DOCKER=1 yedf/dtm:latest`
on: https://en.dtm.pub/deploy/deploy.html#docker-deployment
The preferred and most convenient store for development would be Redis.
`docker pull redis`
`docker run --name mycompany-dev-redis -p 6379:6379 -d redis`

How to enable docker so that DTM container can access to the Redis container?

--------------------------------------

Such sample (with a tutorial on how to establish a development environment - preferably DTM and Redis both in Docker) would be helpful.
With a tiered abp architecture example, and descriptive environment setup (with docker commands), it would be 100% clear where (in which projects inside abp solution) to implement logic.
You can even make an example for Kafka (instead of RabbitMQ) - also preferably run in Docker.

I hope that I gave you a good enough starting point to make a complete example. :)

**Otherwise, thank you for your great work.** 👍 We appreciate it.

**Comment by gdlcf88** [comment]
Thanks for the samples.

This DTM module implements the ABP distributed event bus, which is not only for a tiered or distributed environment but also for monolithic applications. Advanced app developers like you can read and understand the documentation of ABP, Docker and DTM.

So I don't think the tiered apps sample is necessary for the README.
